networks:
  laravel:
    driver: bridge

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_HOME: ${APP_HOME}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
        APP_NAME: ${APP_NAME}
    container_name: laravel
    restart: unless-stopped
    tty: true
    working_dir: ${APP_HOME}/${APP_NAME}/
    volumes:
       - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
       - ./php/php.ini:/usr/local/etc/php/php.ini
       - ./supervisord/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
       - ./supervisord/supervisord.d:/etc/supervisor/conf.d/supervisord.d
       - ./supervisord/cron:/var/spool/cron/crontabs/root
       - ./src:${APP_HOME}/${APP_NAME}/
       - ./.env:${APP_HOME}/${APP_NAME}/.env
    environment:
      - TZ=${APP_TIMEZONE}
    ports:
      - "${PHP_PORT}:${PHP_PORT}"
    networks:
      - laravel
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:${NGINX_PORT_HTTP}"
      - "443:${NGINX_PORT_HTTPS}"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${APP_TIMEZONE}
    depends_on:
      - laravel
      - mysql
    networks:
      - laravel

  mysql:
    platform: linux/x86_64
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=${APP_TIMEZONE} --sql-mode="" --mysql_native_password=ON --performance-schema-consumer-events-statements-cpu=ON --max_connections=3000
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=${APP_TIMEZONE}
    networks:
      - laravel

  mail:
    image: axllent/mailpit:latest
    container_name: mail
    restart: always
    ports:
      - "${MAILPIT_UI_PORT}:${MAILPIT_UI_PORT}"
      - "${MAILPIT_SMTP_PORT}:${MAILPIT_SMTP_PORT}"
    environment:
      - TZ=${APP_TIMEZONE}
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    environment:
      - TZ=${APP_TIMEZONE}
    networks:
      - laravel

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
      - "${JENKINS_AGENT_PORT}:50000"
    volumes:
      - ./jenkins:/var/jenkins_home 
    environment:
      - TZ=${APP_TIMEZONE}
    networks:
      - laravel

volumes:
  jenkins_home:
    driver: local